CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    project_id BIGINT NOT NULL,
    reporter_id BIGINT NOT NULL,
    assignee_id BIGINT,
    title VARCHAR(240) NOT NULL,
    description TEXT,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    priority VARCHAR(40) NOT NULL,
    due_at TIMESTAMPTZ,
    is_overdue BOOLEAN NOT NULL DEFAULT false,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT fk_tickets_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_tickets_reporter FOREIGN KEY (reporter_id) REFERENCES users (id),
    CONSTRAINT fk_tickets_assignee FOREIGN KEY (assignee_id) REFERENCES users (id),
    CONSTRAINT ck_tickets_type CHECK (type IN ('BUG', 'FEATURE', 'TECHNICAL')),
    CONSTRAINT ck_tickets_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE')),
    CONSTRAINT ck_tickets_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);

CREATE INDEX idx_tickets_project_status ON tickets (project_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_assignee_status ON tickets (assignee_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_reporter_id ON tickets (reporter_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_priority ON tickets (priority) WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_due_at ON tickets (due_at) WHERE deleted_at IS NULL;
