CREATE TABLE ticket_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_by BIGINT,
    ticket_id BIGINT NOT NULL,
    depends_on_ticket_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    CONSTRAINT fk_ticket_dependencies_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_ticket_dependencies_depends_on FOREIGN KEY (depends_on_ticket_id) REFERENCES tickets (id),
    CONSTRAINT uk_ticket_dependencies_edge UNIQUE (ticket_id, depends_on_ticket_id),
    CONSTRAINT ck_ticket_dependencies_not_self CHECK (ticket_id <> depends_on_ticket_id),
    CONSTRAINT ck_ticket_dependencies_type CHECK (type IN ('BLOCKED_BY', 'DUPLICATES', 'RELATES_TO'))
);

CREATE INDEX idx_ticket_dependencies_ticket ON ticket_dependencies (ticket_id);
CREATE INDEX idx_ticket_dependencies_depends_on ON ticket_dependencies (depends_on_ticket_id);
