CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    ticket_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    edited_at TIMESTAMPTZ,
    CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_comments_ticket_created ON comments (ticket_id, created_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_comments_author_id ON comments (author_id) WHERE deleted_at IS NULL;

CREATE TABLE mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_by BIGINT,
    comment_id BIGINT NOT NULL,
    ticket_id BIGINT NOT NULL,
    mentioned_user_id BIGINT NOT NULL,
    start_offset INTEGER,
    end_offset INTEGER,
    CONSTRAINT fk_mentions_comment FOREIGN KEY (comment_id) REFERENCES comments (id),
    CONSTRAINT fk_mentions_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_mentions_mentioned_user FOREIGN KEY (mentioned_user_id) REFERENCES users (id),
    CONSTRAINT uk_mentions_comment_user UNIQUE (comment_id, mentioned_user_id),
    CONSTRAINT ck_mentions_offsets CHECK (
        start_offset IS NULL OR end_offset IS NULL OR start_offset <= end_offset
    )
);

CREATE INDEX idx_mentions_user_created ON mentions (mentioned_user_id, created_at);
CREATE INDEX idx_mentions_ticket_id ON mentions (ticket_id);
