CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_by BIGINT,
    actor_type VARCHAR(40) NOT NULL,
    actor_id BIGINT,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT,
    summary VARCHAR(500) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    metadata_json JSONB,
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    CONSTRAINT ck_audit_logs_actor_type CHECK (actor_type IN ('USER', 'SYSTEM'))
);

CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id, created_at);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_type, actor_id, created_at);
CREATE INDEX idx_audit_logs_action_created ON audit_logs (action, created_at);
